---
- name: OverRiding Kernel Defaults `/etc/sysctl.conf` 
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
  become: true
- name: setting limits.conf file
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
  become: true
  notify:
  - update
