---
- name: OverRiding Kernel Defaults `/etc/sysctl.conf` 
  template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
  become: true
- name: setting limits.conf file
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
  become: true
  notify:
  - update
- name: Install java 11
  apt:
    name: openjdk-11-jdk
    state: present
- name: import the postgresql apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true
- name: adding repository to pgdg.list
  shell: "sh -c 'echo \"deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main \" >> /etc/apt/sources.list.d/pgdg.list'"
